### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by sanchoos469** [fox-one/bugs-hunter#54] opened 2019-12-22 14:51 UTC
**Describe the bug**
Incorrect display of the price !!! And the number of coins !!! There is no division by a dot !!!

*Number of coins 2Box. Writes 200Box !!!  Coin price $ 1.8 !!!  He writes $ 18 !!!

**Screenshots**
![20191222_225512](https://user-images.githubusercontent.com/55536421/71323388-2b10f680-251e-11ea-8e4b-4903c9d17cc0.png)

**Information:**
 - Phone OS: Android 7.0
 - Phone Device: Samsung Galaxy 6 edge
 - Phone Version SM-G925F
 - Fox.ONE  App.Version 2.9.0
 - Fox.ONE Referral Code   JJWJM7

**Comment by zhdhr0000** [comment] 2019-12-24 09:55
This question is caused by the different use of decimal points in different countries/areas, it will be fixed in version 2.9.1

**Closed as completed** 2020-03-04 03:10 UTC
Labels: BUG:Low
